version: '3'
services:
  api:
    build: .
    links:
      - 'mongo:mongo'
    environment:
      NODE_ENV: 'development'
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "0.0.0.0:9000:9000"
    command: sh -c "mkdir -p dist && touch ./dist/app.js && nodemon --delay 500ms --watch dist ./dist/app.js"

  transpiler:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    command: ["tsc", "-w"]

  linter:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    command: nodemon --delay 500ms --exec "find . -path ./ -prune -o -path ./node_modules -prune -o -path ./dist -prune -o -name '*.ts' -print | xargs tslint"

  mongo:
    image: mongo:3.6.6
    ports:
      - "27017"
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb
    command: ["mongod"]

  # mocha:
  #   build: .
  #   volumes:
  #     - .:/app
  #   links:
  #     - 'mongo:mongo'
  #   command: nodemon --delay 500ms --exec 'mocha --recursive min --bail --colors' ./dist
  #   environment:
  #     NODE_ENV: 'test'
  #To comentando isso pq preciso resolver um problema mocha vs mongoose

volumes:
  db-data:
  mongo-config:
